### ISSUE TITLE
possible fork?

### ISSUE THREAD

**Issue by ghost** [ghaiklor/backup-my-github#1]
Does this repo has any relation to https://github.com/RomaniukVadim/backup-my-github ?

**Comment by ghaiklor** [comment]
@nuxdie seems like he's just stole it, take a look into first commit - https://github.com/RomaniukVadim/backup-my-github/commit/8e93d4e726eedb924caa271d87c6e71cd03f368c

there is my copyright

but, since I've licensed it under Do What The F*ck You Want... it's not a big deal, imho

**Comment by ghost** [comment]
Cool! Thanks for clarifying that!
