### ISSUE TITLE
Only repo code is being backed up, not the WIki, Issues etc.

### ISSUE THREAD

**Issue by jwbensley** [ghaiklor/backup-my-github#2]
This is a bash script I wrote to backup my GitHub repo's, to include Wiki, Issues, Comments etc. Maybe you could add in these extra features?

https://null.53bits.co.uk/index.php?page=backup-github

The crux of the extra features is as follows:
```
# Wiki backup
git clone https://github.com/jwbensley/$reponame.wiki.git

# Issues backup
curl --silent -L https://api.github.com/repos/jwbensley/$reponame/issues?state=all -o issues.json

# Comments backup
curl --silent -L https://api.github.com/repos/jwbensley/$reponame/issues/comments -o comments.json

# Labels backup
curl --silent -L https://api.github.com/repos/jwbensley/$reponame/labels -o labels.json
```

**Comment by ghaiklor** [comment]
@jwbensley nice, can you make a PR ?

Maybe we could make some different Bash scripts for different situations... I.e. leave my script if someone wants to clone just repos as is, yours if someone wants to clone sources as tar.gz archives along with Wiki, issues, etc...

UPD: could be even separate bash scripts for all of these, anyway it could be executed just by calling bash with `<()`.

**Comment by ghaiklor** [comment]
I've updated script to have a possibility to download archives... though...

there are some edge-case with wikis:
- when wiki is disabled you'll get an error
- when you're trying to clone wiki from your repository (when this is actually a fork, not your repo) you'll get an error as well
